%% Compute the fitness function
function c = fitfun(x,R0,eta,C,son,dt,lan1,f,pop,N,agegrp,t1c,t1a,idealptRf,idealptVf,worstptRf,worstptVf)
%% t1c, t1a is start of vaccination period for children and adults respectively
% deltatc, deltata is duration of vaccination for children and adults
% period and nu1, nu2 is percentage of vaccinated population of children and 
% adults respectively. These values are generated by ga() randomly in an 
% x vector i.e. x=[x(1) x(2) x(3) x(4) x(5) x(6)].
nu1=x(1);nu2=x(2);deltat2=x(3);deltat21=x(4);deltat1=x(5);
t1a=t1c+deltat1;
t2a=t1a+deltat2;t2c=t2a+deltat21; nu=[nu1 nu2];
t=(0:1:son)';dt=0.01;       bet=R0*eta;        nu=[nu1 nu2];
tt1=(0:dt:t1c);tt2=(t1c:dt:t1a);tt3=(t1a:dt:t2a);tt4=(t2a:dt:t2c);tt5=(t2c:dt:son);
TT=[];UU=[];
fun=@(t,y) sirv(t,y,bet,eta,nu,N,C);      arastep
%SONUC= [nu1 R1f5 R2f5 V1f5 V2f5];  PARAMETRE=[nu1 nu2 t2c];
farkRf=((R1f5+R2f5)-idealptRf)/(worstptRf-idealptRf);farkVf=((V1f5+V2f5)-idealptVf)/(worstptVf-idealptVf);
A=[lan1*farkRf (1-lan1)*farkVf];
c=(max(A'))';
end
 